### ISSUE TITLE
Consider switch to zero dependency transformer or...

### ISSUE THREAD

**Issue by scottmarlow** [tbitonti/jakartaee-prototype#101]
Related to [issue#72](https://github.com/tbitonti/jakartaee-prototype/issues/72), some Jakarta EE implementations may not be able to depend on the biz.aQute.bnd:biz.aQute.bndlib library, for various reasons (e.g. they may not already use it or need it). 

Would it make sense to discuss the possibility of depending on a smaller bytecode manipulation library, like ASM?  Perhaps something like [the asm-based-transformer prototype, which isn't directly comparable, as the rule handling is hard coded currently](https://github.com/wildfly-extras/batavia/tree/master/impl/asm-based-transformer).

Another alternative could be [the no-deps-transformer prototype which is closer to the current jakartaee-prototype, in that it is rule file driven](https://github.com/wildfly-extras/batavia/tree/master/impl/no-deps-transformer).

Yet, another approach, could be to inline the biz.aQute.bnd:biz.aQute.bndlib sources that are needed but I'm not sure that I like that approach, as it duplicates/forks BND code, meaning it has to be maintained twice.  Perhaps, there could be other ways of approaching that.

**Comment by bjhargrave** [comment]
I am not sure why a dependency on some other library is OK but on bndlib is not?

Can you be more specific on the concerns? If it is a jar file size issue, I can add a more size friendly jar to the Bnd release which contains the packages needed for transforming.

I am also unclear on what a no-dependency-transformer is? Does that mean writing a new class file processing library?

The Eclipse Transformer project was proposed with a dependency on the bndlib class file processing code. And the project has made significant project, so I don't see the value in taking on the engineering effort to move to another class file processing dependency.

**Comment by scottmarlow** [comment]
> I am not sure why a dependency on some other library is OK but on bndlib is not?

In the case of the ASM dependency, I can talk about the advantages + disadvantages of using ASM. One of the advantages of ASM, is that it uses an expressive visitor API that makes it easy to modify application bytecode in various ways.  I was thinking that if we wanted to handling Class.forName("javax.transaction.TransactionManager") calls in applications, ASM lets us add in bytecode instructions for handling that.  ASM does require some ClassLoader integration code, so its not perfect but shouldn't be that difficult.  I'm not exactly sure if or how we would actually inject code for handling Class.forName() in every application call site.  One disadvantage of ASM, is that a new  constant pool entry is added for every javax => jakarta transformation (the "javax.*" entries are never removed, which is messy). 

Question, if we did modify application bytecode (to handle Class.forName()) someday using bndlib, is that something that has been done before in other projects that use bndlib?  

> Can you be more specific on the concerns? 

If the Eclipse Transformer is included in an Jakarta EE server implementation, the bndlib would also need to be included, however, the bndlib contains much more than transformation code that would not be needed in the Jakarta EE server implementation.

> If it is a jar file size issue, I can add a more size friendly jar to the Bnd release which contains the packages needed for transforming.

Could this be a separate project under https://github.com/bndtools?  That would reduce the amount of code that we need to deal with bringing into WildFly, so I think this would help.

> I am also unclear on what a no-dependency-transformer is? 

It is a transformer prototype that we started, like the ASM one.  The no-dependency-transformer doesn't depend on any other projects.  

> Does that mean writing a new class file processing library?

Yes, it is also yet another class file processing library.  If it is useful, we could integrate it or the ASM based transformer.

**Comment by bjhargrave** [comment]
I can definitely get the Bnd project to produce a more focused library for the transformer which will be smaller. I will work on making this happen.

At this point I don't see that transforming needs to modify bytecodes (method bodies). We can intercept Class.forName (or other interesting calls) by modifying the constant pool entry to point to the intercept method.

**Comment by bjhargrave** [comment]
> I can definitely get the Bnd project to produce a more focused library for the transformer which will be smaller. I will work on making this happen.

I switched to use the smaller Bnd artifact in https://github.com/tbitonti/jakartaee-prototype/commit/eefbb96cb2a7f30c8af6791d1af3ed171f1e1065. So closing this issue.

**Comment by scottmarlow** [comment]
Thanks @bjhargrave for switching to the smaller Bnd artifact!  Very much appreciated!
