### ISSUE TITLE
Should pom metadata be transformed?

### ISSUE THREAD

**Issue by tbitonti** [tbitonti/jakartaee-prototype#108]
Reviewing the yasson project in open-liberty shows these pom metadata files:

```
META-INF/maven/dev/com.ibm.ws.org.eclipse.yasson.1.0/pom.properties
META-INF/maven/dev/com.ibm.ws.org.eclipse.yasson.1.0/pom.xml
```

"pom.properties" contains, for example"

```
version=1.0.40.202005041216
groupId=dev
artifactId=com.ibm.ws.org.eclipse.yasson.1.0
```
Since transformation creates a new artifact, transformation of these files would seem to be necessary, so to match the identify of the new, transformed, artifact.

"pom.xml" for yasson-1.0 has:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>dev</groupId>
  <artifactId>com.ibm.ws.org.eclipse.yasson.1.0</artifactId>
  <version>1.0.40.202005041216</version>
  <description>Eclipse Yasson. Reference implementation of JSR-367 (JSON-B).</description>
  <name>org.eclipse.yasson</name>
  <url>http://www.oracle.com/</url>
  <organization>
    <name>Oracle Corporation</name>
  </organization>
  <licenses>
    <license>
      <name>http://www.eclipse.org/legal/epl-v20.html</name>
      <url>http://www.eclipse.org/legal/epl-v20.html</url>
      <distribution>repo</distribution>
    </license>
    <license>
      <name>http://www.eclipse.org/org/documents/edl-v10.php</name>
      <url>http://www.eclipse.org/org/documents/edl-v10.php</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <scm>
    <connection>scm:git:https://github.com/OpenLiberty/open-liberty.git</connection>
    <developerConnection>scm:git:https://github.com:OpenLiberty/open-liberty.git</developerConnection>
    <url>https://github.com/OpenLiberty/open-liberty/tree/master</url>
  </scm>
</project>


```

**Comment by bjhargrave** [comment]
There is no package information in the pom.xml or pom.properties what would need transforming.

The one reason I can think of needing to transform maven metadata is if one plans to put the transformed jar back into a maven repo. The transformed jar will need new GAV coordinates so that is disambiguated from the original jar. So in that sense, the transformer could need to transform the GAV coordinates in the maven metadata.

**Comment by tbitonti** [comment]
The transformed jar does (or should) have a new identity, which seems to require new pom files.  But, having an added build step to regenerate the files seems perhaps to be a better way to regenerate the files.

**Comment by tbitonti** [comment]
The consensus is that the pom metadata does not currently need to be transformed.  That data, as present in open-liberty, is not being used.
