### ISSUE TITLE
Unable to find:  jakarta-xml-server.properties

### ISSUE THREAD

**Issue by jgallimore** [tbitonti/jakartaee-prototype#88]
Hi - I'm taking a look at this project and trying to get it to run. Apologies if this is a newbie error. I'm trying to run this with the jakarta_snoopy.war file that is provided.

I'm running into this error:

$ ./transformer jakarta_snoopy.war 
Logger name [ Transformer ] (Defaulted)
Log file [ null ]
[main] INFO Transformer - Input     [ ../../../../../../servlet-api/javax_sample_app/snoopy/target/jakarta_snoopy.war ]
[main] INFO Transformer -           [ /home/jgallimore/dev/jakartaee-prototype/dev/transformer/build/distributions/tmp/transformer/bin/../../../../../../servlet-api/javax_sample_app/snoopy/target/jakarta_snoopy.war ]
[main] INFO Transformer - Output    [ ../../../../../../servlet-api/javax_sample_app/snoopy/target/output_jakarta_snoopy.war ] (Generated from input)
[main] INFO Transformer -           [ /home/jgallimore/dev/jakartaee-prototype/dev/transformer/build/distributions/tmp/transformer/bin/../../../../../../servlet-api/javax_sample_app/snoopy/target/output_jakarta_snoopy.war ]
[main] INFO Transformer - Skipping option [ RULES_SELECTIONS ]
[main] INFO Transformer - Using internal [ RULES_RENAMES ]: [ jakarta-renames.properties ]
[main] INFO Transformer - Internal [ RULES_RENAMES ] URL [ jar:file:/home/jgallimore/dev/jakartaee-prototype/dev/transformer/build/distributions/tmp/transformer/lib/transformer.jar!/com/ibm/ws/jakarta/transformer/jakarta-renames.properties ]
[main] INFO Transformer - Using internal [ RULES_VERSIONS ]: [ jakarta-versions.properties ]
[main] INFO Transformer - Internal [ RULES_VERSIONS ] URL [ jar:file:/home/jgallimore/dev/jakartaee-prototype/dev/transformer/build/distributions/tmp/transformer/lib/transformer.jar!/com/ibm/ws/jakarta/transformer/jakarta-versions.properties ]
[main] INFO Transformer - Using internal [ RULES_BUNDLES ]: [ jakarta-bundles.properties ]
[main] INFO Transformer - Internal [ RULES_BUNDLES ] URL [ jar:file:/home/jgallimore/dev/jakartaee-prototype/dev/transformer/build/distributions/tmp/transformer/lib/transformer.jar!/com/ibm/ws/jakarta/transformer/jakarta-bundles.properties ]
[main] INFO Transformer - Using internal [ RULES_DIRECT ]: [ jakarta-direct.properties ]
[main] INFO Transformer - Internal [ RULES_DIRECT ] URL [ jar:file:/home/jgallimore/dev/jakartaee-prototype/dev/transformer/build/distributions/tmp/transformer/lib/transformer.jar!/com/ibm/ws/jakarta/transformer/jakarta-direct.properties ]
[main] INFO Transformer - Using internal [ RULES_MASTER_XML ]: [ jakarta-xml.properties ]
[main] INFO Transformer - Internal [ RULES_MASTER_XML ] URL [ jar:file:/home/jgallimore/dev/jakartaee-prototype/dev/transformer/build/distributions/tmp/transformer/lib/transformer.jar!/com/ibm/ws/jakarta/transformer/jakarta-xml.properties ]
[main] INFO Transformer - All resources will be selected
[main] INFO Transformer - Package renames are in use
[main] INFO Transformer - Package versions will be updated
[main] INFO Transformer - Bundle identities will be updated
[main] INFO Transformer - Using internal [ Substitions matching [ server.xml ] ]: [ jakarta-xml-server.properties ]
[main] INFO Transformer - Internal [ Substitions matching [ server.xml ] ] were not found [ jakarta-xml-server.properties ]
[main] ERROR Transformer - Exception loading rules:
java.io.IOException: Resource [ jakarta-xml-server.properties ] not found on [ class com.ibm.ws.jakarta.transformer.JakartaTransformer ]
	at org.eclipse.transformer.Transformer.loadInternalProperties(Transformer.java:583)
	at org.eclipse.transformer.Transformer$TransformOptions.setRules(Transformer.java:822)
	at org.eclipse.transformer.Transformer.run(Transformer.java:1297)
	at com.ibm.ws.jakarta.transformer.JakartaTransformer.main(JakartaTransformer.java:35)

I'll dig into the code and try and debug this, but at a high-level, am I running the tool correctly, and does this look like a bug, or operator error? Many thanks.

**Comment by tbitonti** [comment]
Hi,

Ah, yes, I ran into this problem myself.  A fix is in branch
'stack-changes', but is not merged yet.

That usage looks correct / normal.

Try out '-u' (usage) for more command line options, and '-v' for extra
output.

Thx!

Thomas F. Bitonti
WebSphere Application Server Group / WCCM
(919) 486-0867
