### ISSUE TITLE
Transform service provider metadata within a bundle

### ISSUE THREAD

**Issue by dazavala** [tbitonti/jakartaee-prototype#97]
First: a bundle may contain a file within directory META-INF/services, named for a javaee service provider interface, which contains the class name of the service provider implementation.

- E.G. file META-INF/services/**javax**.json.bind.spi.JsonbProvider contains class name org.eclipse.yasson.JsonBindingProvider.

**Transform the term "javax" in the file name to "jakarta".** 

- E.G. META-INF/services/**jakarta**.json.bind.spi.JsonbProvider

And second: in order to make this service provider impl class visible to application threads, the bundle will contain liberty service-component metdata for both the javaee service "Provider" and classloading "ResourceProvider".  The XML files for these service-components reside in the OSGi-INF directory.  

**Transform the term "javax" to "jakarta" in the service-component XML files for the service provider and classloading resource provider.**  

E.G.  OSGI-INF/com.ibm.ws.org.eclipse.yasson.JsonBinding**Provider.xml**

`<?xml version="1.0" encoding="UTF-8"?>
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" name="com.ibm.ws.org.eclipse.yasson.JsonBindingProvider" configuration-policy="ignore">
  <property name="implementation.class" type="String" value="org.eclipse.yasson.JsonBindingProvider"/>
  <service>
    <provide interface="javax.json.bind.spi.JsonbProvider"/>
  </service>
  <implementation class="org.eclipse.yasson.JsonBindingProvider"/>
</scr:component>`

Should contain the following after transformation (note the "provide" element "interface" attribute):

`<?xml version="1.0" encoding="UTF-8"?>
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" name="com.ibm.ws.org.eclipse.yasson.JsonBindingProvider" configuration-policy="ignore">
  <property name="implementation.class" type="String" value="org.eclipse.yasson.JsonBindingProvider"/>
  <service>
    <provide interface="jakarta.json.bind.spi.JsonbProvider"/>
  </service>
  <implementation class="org.eclipse.yasson.JsonBindingProvider"/>
</scr:component>`

And E.G. OSGI-INF/com.ibm.ws.org.eclipse.yasson.**ResourceProvider.xml**

`<?xml version="1.0" encoding="UTF-8"?>
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" name="com.ibm.ws.org.eclipse.yasson.ResourceProvider" configuration-policy="require">
  <property name="resources" type="String" value="META-INF/services/javax.json.bind.spi.JsonbProvider"/>
  <service>
    <provide interface="com.ibm.wsspi.classloading.ResourceProvider"/>
  </service>
  <implementation class="com.ibm.wsspi.classloading.ResourceProvider"/>
</scr:component>
`

Should contain the following after transformation (note the "property" element's "value" attribute):

`<?xml version="1.0" encoding="UTF-8"?>
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" name="com.ibm.ws.org.eclipse.yasson.ResourceProvider" configuration-policy="require">
  <property name="resources" type="String" value="META-INF/services/jakarta.json.bind.spi.JsonbProvider"/>
  <service>
    <provide interface="com.ibm.wsspi.classloading.ResourceProvider"/>
  </service>
  <implementation class="com.ibm.wsspi.classloading.ResourceProvider"/>
</scr:component>
`

**Comment by dazavala** [comment]
We worked around this problem by copying an existing build project, that requires transformation, to a new project.  Then in the new project, we enabled the transform, created the META-INF/services service provider file, modified the service-component metadata in the bnd.overrides file, specified the imported packages in the bnd.overrides (due to strange bnd behavior,) modified the bnd.bnd file to instead import the META-INF/services file from the project, and finally, modified build.gradle to remove the vestigial non-transformed jar that published to the build image (could not remove it before publishing due to build errors.)

**Comment by tbitonti** [comment]
Verfied in 0.0.8 using:

```
**jakarta-jsonProvider.properties**
javax.json.bind.spi.JsonbProvider=jakarta.json.bind.spi.JsonbProvider

**jakarta-xml-master.properties**
com.ibm.ws.org.eclipse.yasson.JsonBindingProvider.xml=jakarta-jsonProvider.properties
com.ibm.ws.org.eclipse.yasson.ResourceProvider.xml=jakarta-jsonProvider.properties

**jakarta-renames.properties**
javax.json.bind.spi=jakarta.json.bind.spi
```
